### ISSUE TITLE
not getting message content in alerts

### ISSUE THREAD

**Issue by psifertex** [Zren/quassel-pushbullet#1]
I'm not getting any message content in alerts, just "note: FromNick:". From https://github.com/Zren/quassel-pushbullet/blob/master/plugins/PushbulletNotifications/QuasselPushbullet.js#L140 it looks like it should be, but I'm not sure why it might not be working. Any ideas?

**Comment by Zren** [comment]
So you are getting pushes, but they only have `[#quassel] Zren:` in the title and no message content?

**Comment by psifertex** [comment]
Correct. Looking at the source (and the sample screenshot on the front page) it looks like that shouldn't be the case. 

Ahh, I think I might have found the trouble. quassel-pushbullet is pushing the right message to my phone, but the pushbullet client isn't showing the content in the notification alert. If I view the full notification it's in there. Guess it's not your problem -- unless there's some specific way it's being pushed that causes that?

**Comment by Zren** [comment]
Ah, I have it set so it puts the message in the title as well and the "contents" are a url. This is so pushbullet treats the push as a link instead of just text so you can open the webserver without opening the push in pushbullet first. 

Try replacing [these lines](https://github.com/Zren/quassel-pushbullet/blob/master/plugins/PushbulletNotifications/QuasselPushbullet.js#L136-L141) with

``` js
    title += ' ' + message.content;
    body = '';
```

**Comment by Zren** [comment]
Just realized the screenshots still show when I only put webserver url after the message in the contents. Still, not sure why your phone wouldn't show the pushbullet contents in the notification.

**Comment by psifertex** [comment]
Yup, that did it. I'm not planning on using the link for a web interface so I'll just leave it like that. Thanks.
